### ISSUE TITLE
Unable to generate valid code for array of enums

### ISSUE THREAD

**Issue by bemnetmerha-db** [OpenAPITools/sbt-openapi-generator#41]
Using this plugin version, I am not able to generate valid array of enums. 

```
addSbtPlugin(dependency =
  "org.openapitools" % "sbt-openapi-generator" % "5.0.1"
)
```

1. Create api spec with this

```
        object_permissions:
          type: array
          description: Required list of Object ACLs
          items:
            type: string
            enum:
              - Test1
              - Test2
```
2. run code gen using  `sbt openApiGenerate` and config 

```
openApiHttpUserAgent: "databricks-test"
generatorName: "scala-akka"
outputDir : "generated"
openApiGenerateApiTests: "true"
modelPropertyNaming: "original"
openApiGenerateApiDocumentation: "true"
openApiGenerateModelDocumentation: "true"
```

4. Generated invalid code with no enum values.
```  case class Config (
  /* Required list of Object ACLs */
  object_permissions: Option[PartnerConfigEnums.Seq[ObjectPermissions]] = None,
) extends ApiModel

object PartnerConfigEnums {
  type Seq[ObjectPermissions] = Seq[ObjectPermissions].Value
  object Seq[ObjectPermissions] extends Enumeration {
  }
}
```
